- name: F1Score
  class: F1Metric
  params:
    use_pitch_class: true
    min_time_unit: 0.02

- name: KeyCorrelation-a
  class: KeyCorrelationMetric
  params:
    segment_duration: 0.2

- name: KeyCorrelation-b
  class: KeyCorrelationMetric
  params:
    segment_duration: 0.1
    use_weighted: false
