- name: confusion metrics
  class: F1Metric
  params:
    use_pitch_class: true
    min_time_unit: 0.02

- name: key correlation
  class: KeyCorrelationMetric
  params:
    segment_duration: 0.2

- name: KeyCorrelation-b
  class: KeyCorrelationMetric
  params:
    segment_duration: 0.1
    use_weighted: false

- name: DstartDistribution
  class: DstartCorrelationMetric

- name: DurationDistribution
  class: DurationCorrelationMetric

- name: velocity distribution
  class: VelocityCorrelationMetric

- name: pitch distribution
  class: PitchCorrelationMetric
